### ISSUE TITLE
Unclear on step 2. copy the ".exe and .config"

### ISSUE THREAD

**Issue by fbarletta** [robertmiles3/svn-slack-notifier#6]
> Copy the .exe and .config files from the latest Release into a folder of your choosing that is accessible from your svn server.

I'm unclear on where the .exe and .config are coming from. The repo does not have a .exe and I am unsure of which .exe (if from visualsvn) I should be using.

Any help is appreciated.

**Comment by robertmiles3** [comment]
When you build the project, it will output these files (like any .Net project does).

**Comment by fbarletta** [comment]
Great.

I would just make that clear for anyone else who wishes to use this.

Worked great by the way!
