### ISSUE TITLE
commit changes

### ISSUE THREAD

**Issue by via-joepaduano** [robertmiles3/svn-slack-notifier#9]
Hello.  is there a way to get more information about the svn commit - im just getting 
New commit by _username_
rev#: _comment_

using: 
"D:\svn-slack-notifier\SVNSlackNotifier.exe" -path=%1 -rev=%2 _-name=_SVNrepo-name_ -url=_SVNrepo-url_/trunk

was looking for something like
New commit by _username_
rev#: _comment_
repo: _repoURL_
dif: _dif_

thank you - Joe.

**Comment by robertmiles3** [comment]
Feel free to take a look at the source code. I switched to git years ago and no longer use SVN anymore so I'm unable to do anything more with this.

**Comment by via-joepaduano** [comment]
ok - thanks for getting back to me Robert.  looks like its time to move on as well (to Git).  only using VisualSVN because of the AD integration.  thanks again though.
